name: Mention UX Team

on:
  workflow_call:
    inputs:
      id:
        required: true
        type: number

jobs:
  add-comment:
    if: github.event.label.name == 'ux-review'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Mention UX Team in comments
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ inputs.id }}
          body: |
            Head's up @configcat/ux-qa-team - someone needs a UX review!
