name: Mention UX Team

on:
  workflow_call:
    inputs:
      id:
        required: true
        type: number
      repo:
        required: true
        type: string
    secrets:
      gh_token:
        required: true

jobs:
  ux-review-comment:
    if: github.event.label.name == 'ux-review'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Mention UX Team in comments
        run: gh issue comment "$NUMBER" --repo "$REPO" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
          NUMBER: ${{ inputs.id }}
          REPO: ${{ inputs.repo }}
          BODY: |
            Head's up @configcat/ux-qa-team - someone needs a UX review!
            
  text-review-comment:
    if: github.event.label.name == 'text-review'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Mention Text Team in comments
        run: gh issue comment "$NUMBER" --repo "$REPO" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
          NUMBER: ${{ inputs.id }}
          REPO: ${{ inputs.repo }}
          BODY: |
            Head's up @configcat/text-reviewers - someone needs a text review!
      - name: Trigger Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "pr_name": "${{ github.event.pull_request.title }}",
              "pr_url": "${{ github.event.pull_request.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
